repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        name: "Ensuring files end with a newline"
        types: [python]
      - id: trailing-whitespace
        name: "Removing trailing whitespace"
        types: [python]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: "Prettifying code (Black)"
        types: [python]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: Sorting imports (isort)
        types: [python]
        args:
          - "--profile=black"
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        name: "Preventing technical debt (Pylint)"
        types: [python]
        args:
          - "--disable=E0401,R0801,C0411"
          - "--good-names=i,j,k,ex,Run,_,df,ax,fig,plt,x,y,f"
          - "--max-line-length=88"
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: "Enforcing pep8 (Flake8)"
        types: [python]
        args:
          - "--max-line-length=88"
          - "--ignore=E203,W503"
  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
      - id: pydocstyle
        name: "Checking your docstrings (Pydocstyle)"
        types: [python]
        args:
          - "--convention=google"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
        name: "Forcing static typing (Mypy)"
        types: [python]
        args:
          - "--ignore-missing-imports"
          - "--disable-error-code=import"
          - "--disable-error-code=attr-defined"
          - "--disable-error-code=name-defined"
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: "Ensuring security (Bandit)"
        types: [python]
